### ISSUE TITLE
Раньше были произведения с других сайтов

### ISSUE THREAD

**Issue by purpleraven** [crazy-tea-party/grouple-recsys-production#15]
например на риде были еще минт и селфманга.

**Comment by purpleraven** [comment]
но произведения с других сайтов должны иметь вес чуть ниже.  Но например с rumix -- выше. 
Так что надо что-то придумать

**Comment by Kolyada** [comment]
В результате наработки для смежных сайтов оставлены в отдельной ветке (настройка через конфиг, без весов)
