### ISSUE TITLE
Моделька пустая на selflib

### ISSUE THREAD

**Issue by purpleraven** [crazy-tea-party/grouple-recsys-production#17]
explorations выдает пусто

**Comment by Kolyada** [comment]
Файл explorational_recs.json в папке selflib пустой.
Его можно сформировать повторно из ноутбука notebooks/initial_recs.ipynb
Для повторного формирования файла необходимы файлы genres.json и items_features.csv
Не могу найти, как их формировать, ты не знаешь?

**Comment by purpleraven** [comment]
а примеры данных в genres.json и items_features.csv есть? 
предполагаю что эти данные из element таблицы как-то собираются

**Comment by Kolyada** [comment]
Добавлен файл для генерации explorational_recs.json /database/explorations/explorations.py
