### ISSUE TITLE
Прикрутить нормальный логгер

### ISSUE THREAD

**Issue by purpleraven** [crazy-tea-party/grouple-recsys-production#18]
Сейчас есть лог обращений и системный лог.

Все ошибки должны писаться в системный лог (logger.add('logs/' + config.name + '-server.log'))

сейчас для написания лога надо писать так:

```
with open('logs/' + self.config.name + '-usage.log', 'a') as f:
            logger.info(f'similarItems item_id={iid} n_recs={n_recs}') 
```

хочется чтоб было 
```
           usageLogger.info(f'similarItems item_id={iid} n_recs={n_recs}') 
```

так же добавить в системный лог информацию по основным фазам:
загрузка, начал читать из базы, закончил читать, запустился пересчет модели (где-то это есть)

**Comment by Kolyada** [comment]
Я прикрутил логгер loguru (он там и был).

Регистрируем файлы в server.make_log :
- logs/selfmanga-usage.log - logger.info('TEXT")
- logs/selfmanga-server.log - logger.debug('TEXT")
- logs/selfmanga-error.log - @logger.catch

А также добавил логи в http_utils.recalculate_handler.get
