### ISSUE TITLE
Зачем нужен recalculate когда есть rateItem

### ISSUE THREAD

**Issue by purpleraven** [crazy-tea-party/grouple-recsys-production#19]
внутри у нас like и bookmark как минимум сейчас сводятся к одной таблички
я могу по заклаке и оценке тоже rateItem дергать и все
почему нет??

**Comment by purpleraven** [comment]
или патчить модель не всегда хорошо?
я легко могу добавить дерганье для букмарка
наверное иногда все-таки надо  будет полностью пересчитывать, раз в сутки или в неделю.

**Comment by Kolyada** [comment]
rateItem работает с пользователем.
2022-04-02 21:37:08.876 | INFO     | http_utils.updating.rate_item_handler:post:27 - rateItem item_id=12176 user_id=53724 pos=1
Я думаю полный пересчет модели возможен только пересозданием через recalculate.
Дополнительно я проверил на readmanga (порт 5001) - пока делается пересчет модели, запросы доступны.

**Comment by purpleraven** [comment]
И так понимаю для новых пользователей тоже все норм будет?

тогда предлагаю так сделать, все новые данные заливать через rateItem , добавив туда status и rate дописав немного кода. 
А recalculate дергать я буду например раз в неделю ночью.
Если ок, то надо в рамкамх этой задачи расширить функционал rateItem
Логику преобразования статуса в rate посмотреть можно в загрузке из базы. Потом загрузку из базы тоже переделать надо будет на загрузку чистых данных и преобразование данных в python  коде а не в sql

**Comment by Kolyada** [comment]
Функционал rateItem расширен (добавлен status)
Новые пользователи добавляются прямо в rateItem (это было сразу)
recalculate можно запускать редко (раз в сутки)
Во время его работы сервисы не должны переставать работать
