### ISSUE TITLE
Рейтинг везде 1..10

### ISSUE THREAD

**Issue by purpleraven** [crazy-tea-party/grouple-recsys-production#20]
у меня везде рейтинг 1..10
Но тут получается значение 0 и 10
```
if positive is not None:
    rate = float(positive) * 10
```
надо поменять в коде??

в запросе я это уже поправил

**Comment by Kolyada** [comment]
В логах есть такие строки:
```
2022-04-02 21:36:54.905 | INFO     | http_utils.updating.rate_item_handler:post:27 - rateItem item_id=12176 user_id=53724 pos=0
2022-04-02 21:37:08.876 | INFO     | http_utils.updating.rate_item_handler:post:27 - rateItem item_id=12176 user_id=53724 pos=1
```
Соответственно и результат будет (0 || 1) * 10 = 0 || 10
Я добавил в логи полный список параметров: 
`logger.info(f'rateItem item_id={iid} user_id={uid} positive={positive} rate={rate}')`

> у меня везде рейтинг 1..10
В таблице bookmark есть разные значения rate: null, 0, 1?

**Comment by purpleraven** [comment]
надо сделать чтоб 1 или 10 там был.
```
positive ? 10: 1
```

**Comment by Kolyada** [comment]
Исправил логику в dataloader и rateItem - теперь рейтинг в интервале 1..10
У rateItem порядок такой: positive (1,10) -> rate (1..10) -> status (4:3, 7,8: 10; 3,5: 5) -> default 7.
